---
version: "3.7"
services:
  sonarr-exporter:
    image: onedr0p/exportarr:master
    entrypoint: ["exportarr"]
    command: ["sonarr"]
    environment:
      PORT: 9707
      URL: "http://192.168.1.100:8989"
      APIKEY: "amlmndfb503rfqaa5ln5hj5qkmu3hy18"
      ENABLE_EPISODE_QUALITY_METRICS: "false"
    ports:
      - "9707:9707"
  radarr-exporter:
    image: onedr0p/exportarr:master
    entrypoint: ["exportarr"]
    command: ["radarr"]
    environment:
      PORT: 9708
      URL: "http://192.168.1.100:7878"
      APIKEY: "amlmndfb503rfqaa5ln5hj5qkmu3hy18"
    ports:
      - "9708:9708"
